### ISSUE TITLE
Error message pops up when running Main.py

### ISSUE THREAD

**Issue by billyau615** [elpideus/tgbiofy#1]
Hi ! I had installed pip install termcolor, pip install spotipy, pip install urllib3 and pip install Telethon. When I do python Main.py, it pops up   

File "Main.py", line 25
    async def main():
            ^
SyntaxError: invalid syntax

How can I fix this issue? Thanks 
Thank you for your time : )
OS environment Ubuntu 20.04 LTS
VPS environment : Oracle AMD instance

**Comment by elpideus** [comment]
Sport for the late answer but it probably has been solved in the new version.

**Comment by elpideus** [comment]
Going to solve this as soon as possible. In three days it will probably be fixed. I will update you if the time will be longer.

**Comment by elpideus** [comment]
> Hi ! I had installed pip install termcolor, pip install spotipy, pip install urllib3 and pip install Telethon. When I do python Main.py, it pops up
> 
> File "Main.py", line 25 async def main(): ^ SyntaxError: invalid syntax
> 
> How can I fix this issue? Thanks Thank you for your time : ) OS environment Ubuntu 20.04 LTS VPS environment : Oracle AMD instance

Hello, I just tried it and it works just fine. Can you please tell me the Python version that you are using?

**Comment by billyau615** [comment]
Hi! That’s Python 3.6, thanks

**Comment by elpideus** [comment]
> Hi! That’s Python 3.6, thanks

Ok, I will test it out, sorry for the long time answers. Did you do any edits to the code? Also, could you send me your config file (alter your credentials in the file before showing it so no one will steal your info). 
Also the full error message would be really useful.
It would help me a lot solving your problem. Thanks and sorry for the inconvenience.

**Comment by worldomonation** [comment]
The key (in my case) was to explicitly call `python3` despite using a `virtualenv` created with Python 3.9.

1. install `pyenv` and `pyenv-virtualenv`
2. create a virtual environment using Python 3.9.
3. install dependencies with `pip3 install -r requirements.txt`.
4. run using `python3 Main.py`.

```
(py39) ➜  ~/workspace/tgbiofy git:(master) ✗ python3 Main.py
Please enter your phone (or bot token): <your_phone_number>
Please enter the code you received: <2fa_code>
Signed in successfully as <name>
```
