### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI opens up after start

### ISSUE THREAD

**Issue by SirRancore** [elpideus/tgbiofy#10]
Hello, I followed all the steps and finally after some tries got it to work. Or at least, so I thought. I logged after opening "Main.py" and the message "Program has been booted" followed in green. In my browser a tab opens, but it just says "INVALID_CLIENT: Invalid redirect URI" in a white background. The link start with "https://accounts.spotify.com/authorize?client_id...". How can I fix this?
![immagine](https://github.com/user-attachments/assets/2636b513-fbb0-4c14-8b7d-0396739531ff)

**Comment by elpideus** [comment]
![image](https://github.com/user-attachments/assets/b7c7afd4-323a-4dce-aaa5-f287eae6a532)

Try adding these two as the redirect URIs in your Spotify developer dashboard.

**Comment by SirRancore** [comment]
I found out that changing the redirect URL in the "configuration.ini" file from "http://localhost:8888" to "http://localhost:8888/callback" solves the issue (at least it did for me). Thank you, very cool program by the way!
