### ISSUE TITLE
Running fine but no change on telegram profile info

### ISSUE THREAD

**Issue by wokawoka** [elpideus/tgbiofy#2]
First of all thank you very much for sharing this nice script. 

I did set it up by following your readme, the program is running fine (I get "Program has been booted") and it appears that it correctly listens to port 8080 (if I try to connect to localhost:8080 with a browser the program throws out some errors and stops) but still, according to the spotify for developers app page there are no requests, and indeed there's no chenge on the telegram profile info.

Any suggestion on where I could look for something I've missed or a misconfiguration?

Thank you very much again for your great work!

**Comment by elpideus** [comment]
Hi. First of all sorry for the late answer and thanks for using the script.

It should automatically open a browser tab and load the localhost url. It is not a manual operation. Also, i recently updated the readme. Did you add the localhost:8080 to your redirect in the spotify app settings on the spotify dashboard?

**Comment by wokawoka** [comment]
> Hi. First of all sorry for the late answer and thanks for yousing the script.

No problem, thank you very much for your answer!

> It should automatically open a browser tab and load the localhost url. It is not a manual operation. Also, i recently updated the readme. Did you add the localhost:8080 to your redirect in the spotify app settings on the spotify dashboard?

Thank you for updating the readme with all the details. I did indeed include the localhost:8080 to the redirect in the spotify app.
Everything looks correct to me, the script is not opening the browser tab though, and it might depend on my specific setup, I suppose, since I remember to have had similar issues with other terminal programs not being able to properly open the browser in the past.
I'm running pop os 21.10 and KDE 5.22.5 if it can help.

**Comment by wokawoka** [comment]
I will try to investigate more on my specific setup and see if I can fix my problem with the terminal not being able to open the browser.

But do you by chance think that there might be a chance to modify the script to pass the data directly without having to go through the default browser of the system?

Thank you again

**Comment by elpideus** [comment]
Closing for no updates
