### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by stepersy** [elpideus/tgbiofy#4]
Hi, thanks for your fantastic project! Could you please make it an Heroku Deployable project? It could be very useful to let it continue in background without having a server. Thanks!

**Comment by elpideus** [comment]
Hello. 

First of all i want to thank you for using tgbiofy.
You can easily run this script on heroku without needing it to be a deployable project. You only need to set a worker (for example: heroku ps:scale worker=1)

Maybe in the future I will consider making this project a heroku deployable project. As for now it isn't needed as not many people are using it.
