### ISSUE TITLE
Line 5 module name telethon 

### ISSUE THREAD

**Issue by coffeeadicto** [elpideus/tgbiofy#5]
Line 5 module name telethon

**Comment by elpideus** [comment]
Can you please send the entire error?

Also sorry for the late reply.

**Comment by lilithnicolaievna** [comment]
~~~~~~~~~~~~~~~~~~  ^
      20 warnings and 14 errors generated.

**Comment by lilithnicolaievna** [comment]
> Line 5 module name telethon

this is actually the first of my errors

**Comment by elpideus** [comment]
Sorry for the late reply. I had some problems with my GitHub account. 
Anyway you may need to install the Telethon library.

```python3 -m pip install --upgrade telethon```
