### ISSUE TITLE
Getting logged out of the Telegram account on all devices

### ISSUE THREAD

**Issue by NaskelRoss** [elpideus/tgbiofy#7]
After using the script, it logs out of the account on all devices. When trying to log in, it allows one to use the account for about 30 seconds and then logs out again, even when the script is turned off. After a few attempts, it blocks the access to the account stating "Too many tries."

**Comment by elpideus** [comment]
Maybe something changed on Telegram's end. I will check.

**Comment by elpideus** [comment]
Fixed with new version.
