### ISSUE TITLE
It's not installing all the requirements

### ISSUE THREAD

**Issue by ned986** [elpideus/tgbiofy#9]
It's not installing all the requirements when running pip3 install -r requirements.txt

**Comment by ned986** [comment]
Hello?

**Comment by elpideus** [comment]
Hi.

First of all I am sorry for the late reply. If you haven't fixed it yet, could you show me the error that you're getting when you're trying to execute `pip3 install -r requirements.txt`?

Thank you very much.

**Comment by elpideus** [comment]
Hello.

Sorry for the late response.

The issue should now be fixed. Just make sure that you are running Python 3.13. If possible setup a clean venv and run the script there. 

Feel free to open this issue if other problems come up.

**Comment by ned986** [comment]
Same errors. The version and everything else is correct

**Comment by elpideus** [comment]
Strange, it seems to be working perfectly though...

![image](https://github.com/user-attachments/assets/2751c6b3-9a62-4386-972c-180267ff4560)

It runs as well:
![image](https://github.com/user-attachments/assets/e74a4790-aec0-4a1e-8532-317c86f1c518)
